### ISSUE TITLE
关于两个细节问题

### ISSUE THREAD

**Issue by yuhua666** [SteveTsui/IDa-Det#2]
博士您好，我有如下疑问，期待您的解答：
1.我注意到您的代码里使用了Shared2FCBBoxHead，这个检测头包含了较大的参数量和计算量，为什么您没有使用参数量、计算量较小的BBoxHead呢？
2.相较于全精度网络，您的二值化网络使用了更小的学习率和batchsize，这是为什么？

**Comment by SteveTsui** [comment]
您好，Shared2FCBBoxHead是跟mmdet官方的Faster-RCNN+FPN保持一致。
更小的batch size是因为显卡显存有现，而1bit网络由于训练时存在较多的fake quantization操作，占据的显存会比全精度网络大很多，所以我们只能降低batchsize，同时根据经验降低了学习率。

**Comment by yuhua666** [comment]
感谢您的回复，我注意到Shared2FCBBoxHead会占用比较大的参数量、计算量
我自己在Faster rcnn+resnet18上试过，当我不更换检测头，只二值化时，跟不二值化只更换检测头为BBoxHead的参数量接近。
因此我产生了一个疑问，仍使用Shared2FCBBoxHead的二值化网络达到了一个怎样的目的呢？期待您的再次指导。

**Comment by SteveTsui** [comment]
您好，在做实验时我没有考虑到这个细节，文章中的FLOPs计算均是按照Shared2FCBBoxHead来计算，如果使用BBoxHead能得到相近的性能，并更多的减少计算量，应该会是更好的结构设置，我会尽快测试这个结构并同步。
